Feature/detekt setup
kotrasatheesh-dev/RicckyAndMorty pull request #2
Opened 2024-12-24 11:01 UTC by kotrasatheesh-dev

initial setup of detekt and required files

2024-12-30 14:05 UTC, shreyansh-mm requested changes
We are missing github action for detekt.
This action needs to run on every PR automatically.

2024-12-30 14:05 UTC, shreyansh-mm commented on app/src/main/java/com/rickyandmonty/ui/ui/theme/Color.kt
This should be moved to a different module, should not be in app module.

2024-12-30 14:05 UTC, shreyansh-mm commented on app/src/main/java/com/rickyandmonty/ui/ui/theme/Theme.kt
This should be moved to a different module, should not be in app module.

2024-12-30 14:05 UTC, shreyansh-mm commented on app/src/main/java/com/rickyandmonty/ui/ui/theme/Theme.kt
> +     */
Remove the commented code.

2024-12-31 04:56 UTC, kotrasatheesh-dev commented on app/src/main/java/com/rickyandmonty/ui/ui/theme/Color.kt
multi module setup not done yet once it is done i will add

2024-12-31 04:56 UTC, kotrasatheesh-dev commented on app/src/main/java/com/rickyandmonty/ui/ui/theme/Theme.kt
multi module setup not done yet once it is done i will add

2024-12-31 07:08 UTC, shreyansh-mm approved these changes

2024-12-31 07:16 UTC, merged